export const products = [
    {
      id: "VvIeTGGmrPNt7SzomQh4",
      name: "iphone 14",
      description: "Short description",
      price: 2999,
      brand: "apple",
      category: "Phone",
      inStock: true,
      image: "https://firebasestorage.googleapis.com/v0/b/products-c9eb0.appspot.com/o/products%2F61bK6PMOC3L._AC_UF1000%2C1000_QL80_.jpg?alt=media&token=b23aaae5-0bc6-4397-9364-b147cb19077e",    
      reviews: [],
    },
    {
      id: "6G6rieWw14yEtxQ99qWI",
      name: "Logitech MX",
      description:
        "PERFECT STROKE KEYS - Spherically-dished keys ",
      price: 10099,
      brand: "logitech",
      category: "Accesories",
      inStock: true,
      image: "https://firebasestorage.googleapis.com/v0/b/products-c9eb0.appspot.com/o/products%2F61bK6PMOC3L._AC_UF1000%2C1000_QL80_.jpg?alt=media&token=b23aaae5-0bc6-4397-9364-b147cb19077e",   
      reviews: [],
    },
    {
      id: "VvIeTGGmrPNt7SzomQh4",
      name: "Apple iPhone 12, 64GB",
      description:
        'The product is refurbished, fully functional, and in excellent condition.',
      price: 40000,
      brand: "Apple",
      category: "Phone",
      inStock: true,
      image: "https://firebasestorage.googleapis.com/v0/b/products-c9eb0.appspot.com/o/products%2F61bK6PMOC3L._AC_UF1000%2C1000_QL80_.jpg?alt=media&token=b23aaae5-0bc6-4397-9364-b147cb19077e",    
      reviews: [],
    },
    {
      id: "FcO4ya265WKE9mm07XeD",
      name: "Logitech MX Master ",
      description:
        "Cross computer control: Game changing capacity to navigate seamlessly on 3 computers, and copy paste text, images, and files from 1 to the other using Logitech flow\nDual connectivity: Use with upto 3 Windows or Mac computers via included Unifying receiver or Bluetooth Smart wireless technology.",
      price: 30000,
      brand: "logitech",
      category: "Accesories",
      inStock: true,
      image: "https://firebasestorage.googleapis.com/v0/b/products-c9eb0.appspot.com/o/products%2F61bK6PMOC3L._AC_UF1000%2C1000_QL80_.jpg?alt=media&token=b23aaae5-0bc6-4397-9364-b147cb19077e",   
      reviews: [],
    },
    {
      id: "VKHN6ldapuHKSWXE6ZMS",
      name: 'Smart Watch(Answer/Make Call)',
      description:
        'Bluetooth Call and Message Reminder: The smart watch is equipped with HD speaker, after connecting to your phone via Bluetooth, you can directly use the smartwatches to answer or make calls, read messages, store contacts, view call history.',
      price: 5000,
      brand: "Nerunsa",
      category: "Watch",
      inStock: true,
      image: "https://firebasestorage.googleapis.com/v0/b/products-c9eb0.appspot.com/o/products%2F61bK6PMOC3L._AC_UF1000%2C1000_QL80_.jpg?alt=media&token=b23aaae5-0bc6-4397-9364-b147cb19077e",    
      reviews: [],
    },
  ];